#!/bin/sh
. "$(dirname "$0")/func_testsuite.sh"

init_suite "ECHO BUILTIN"

run_test "echo test"
run_test "echo a b c"
run_test "echo '  espaces  '" 
run_test "echo"
run_test "echo -n A; echo B"
run_test "echo -n -n A; echo B"
run_test "echo -n A B C; echo D"
run_test "echo -e 'Ligne1\nLigne2'"
run_test "echo -e 'A\tB'"
run_test "echo -e '\\\\'" 
run_test "echo -E 'A\nB'" 
run_test "echo -E '\\\\'"
run_test "echo '\\\\'"
run_test "echo -ne 'A\nB'; echo C" 
run_test "echo -en 'A\nB'; echo C"
run_test "echo -eE '\\\\'"
run_test "echo -Ee '\\\\'"
run_test "echo -EeE '\\\\'"
run_test "echo -nEe '\\\\'; echo suite"
run_test "echo -x"      
run_test "echo -n -x"      
run_test "echo -nx"     
run_test "echo -"                
run_test "echo -n -"

end_suite "ECHO BUILTIN"