#!/bin/sh
. "$(dirname "$0")/func_testsuite.sh"

init_suite "LEXER"

run_test "ls -l"
run_test "echo 'hello; world'"
run_test "echo 'if then else'"
run_test "ls # comment"
run_test "echo A #; echo B"
run_test "echo A
echo B"
run_test "echo 'a'b"
run_test "echo a'b'"
run_test "echo \"a\"b"
run_test "echo a\"b\""
run_test "echo \"a\"'b'"
run_test "echo 'a'\"b\""
run_test "ls 'if'"
run_test "ls \"if\""
run_test "ls \if"
run_test "ls \"while\""
run_test "ls 'for'"
run_test "echo 'a|b'"
run_test "echo \"a|b\""
run_test "echo 'a>b'"
run_test "echo \"a;b\""
run_test "echo \"a&b\""
run_test "echo ''"
run_test "echo \"\""
run_test "echo \"\"''"
run_test "echo \\" 
run_test "echo \a"
run_test "echo \;"
run_test "echo \|"
run_test "echo \>"
run_test "echo a\ b"
run_test "echo a\ b\ c"
run_test "echo \"a\"\ b"
run_test "echo %"
run_test "echo ^"
run_test "echo % ^ \ : ;"
run_test "echo \#"
run_test "echo '\\'"
run_test "echo \"\\'\""
run_test "echo '\"'"
run_test "echo"
run_test "echo \ "

rm -f b
end_suite "LEXER"


